CREATE TABLE USER (
	userID VARCHAR(50) NOT NULL,
	userPassword VARCHAR(255) NOT NULL,
	userEmail VARCHAR(100) NOT NULL,
	CONSTRAINT PRIMARY KEY(userID)
);


CREATE TABLE DOG ( 
	userID VARCHAR(50) NOT NULL, 
	dogName VARCHAR(50) NOT NULL, 
	dogAges VARCHAR(10) NOT NULL, 
	dogWeight DOUBLE NOT NULL, 
	CONSTRAINT PRIMARY KEY(userID, dogName), 
	CONSTRAINT FOREIGN KEY(userID) REFERENCES USER(userID) on DELETE CASCADE 
);

CREATE TABLE FOOD ( 
	userID VARCHAR(50) NOT NULL, 
	foodName VARCHAR(50) NOT NULL,
	protein DOUBLE NOT NULL, 
   	fat DOUBLE NOT NULL,
    	fiber DOUBLE NOT NULL,
	CONSTRAINT PRIMARY KEY(userID, foodName), 
	CONSTRAINT FOREIGN KEY(userID) REFERENCES USER(userID) on DELETE CASCADE 
);

CREATE TABLE WALK(  
	userID VARCHAR(50) NOT NULL,  
	walkContent VARCHAR(10000) NOT NULL,  
	walkName VARCHAR(1000) NOT NULL,  
	walkDate DATE NOT NULL,  
	CONSTRAINT FOREIGN KEY(userID) REFERENCES USER(userID) on DELETE CASCADE  
); 


CREATE TABLE WALKNOTICE( 
	noticeContent VARCHAR(1000) NOT NULL,
	noticeName VARCHAR(50) NOT NULL,
	noticeDate DATE NOT NULL
);